### ISSUE TITLE
NullPointerException when loading the version list in the context menu

### ISSUE THREAD

**Issue by vatbub** [vatbub/fokLauncher#46]
Open the launcher -> Wait for online mode to be enabled -> Right-click Hangman solver (new versions) -> Open the "Launch a specific version" menu -> List keeps loading forever due to this exception:

```
[SEVERE] An uncaught exception occurred in the thread buildContextMenuThread
java.lang.NullPointerException
        at java.util.Collections.sort(Unknown Source)
        at applist.App.lambda$null$5(App.java:1351)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by vatbub** [comment]
Additional note: No Version of Hangman solver was installed on the machine
